package com.saatiril.andro.data

import android.content.Context
import android.os.Build
import android.provider.Settings
import com.google.gson.JsonParser
import java.security.MessageDigest
import java.util.Calendar
import java.util.Locale
import javax.crypto.Mac
import javax.crypto.spec.SecretKeySpec
import kotlin.math.ceil

/**
 * SAATIRIL — License System (Android port of `electron/license.ts`).
 *
 * The activation CODE algorithm matches the Electron implementation EXACTLY
 * so that codes are interchangeable across platforms:
 *  - A code generated by the Electron tool (`tools/generate-license.ts`),
 *    the Next.js API route (`/api/generate-license`), or this class's
 *    [generateCode] for a given Machine ID will validate against that same
 *    Machine ID on any platform.
 *
 * Note: the Machine ID itself is platform-specific by design.
 *   - Electron uses cpu|cores|mac|hostname|platform|arch
 *   - Android  uses manufacturer|model|board|androidId|serial
 * A code is always bound to the device it was generated for; only the CODE
 * algorithm has to match across platforms, and it does.
 *
 * License policy (matches Electron):
 *  - Type:    "monthly" (only type supported)
 *  - Validity: 30 days from code-generation date, expiry pinned to
 *              23:59:59.000 LOCAL TIME on the expiry day.
 *  - No grace period — activation required on first launch.
 *  - After expiry, the user must request a new code.
 *
 * Persistence:
 *  - SharedPreferences key `"license_data"`.
 *  - Stored value: `payloadJson + "." + hmac` where hmac = HMAC-SHA256
 *    keyed by SHA-256(LICENSE_SECRET) over payloadJson.
 *  - payloadJson = `{"type":"monthly","activatedAt":<millis>,"expiry":<millis>,"code":"XXXX-XXXX-XXXX-XXXX"}`
 *  - On load: verify HMAC, then RE-VERIFY the code against the current
 *    device's Machine ID (this is what binds the stored license to the
 *    device — copying the blob to a different device fails this check).
 */
class LicenseManager(private val context: Context) {

    // ── Configuration ──────────────────────────────────────────────────────
    companion object {
        /** Same secret as electron/license.ts, route.ts, tools/generate-license.ts. */
        private const val LICENSE_SECRET = "SAATIRIL-2026-HUMAS-UIN-ANTASARI-BANJARMASIN"

        private const val LICENSE_TYPE_MONTHLY = "monthly"
        private const val MONTHLY_VALIDITY_DAYS = 30

        /** Brute-force window for verification — matches Electron's 0..45 day range. */
        private const val VERIFY_MAX_DAY_OFFSET = 45

        /** Number of hex chars taken from SHA-256 of the code input (XXXX-XXXX-XXXX-XXXX = 16). */
        private const val CODE_HASH_LENGTH = 16

        private const val PREFS_NAME = "saatiril_license"
        private const val KEY_LICENSE_DATA = "license_data"
    }

    // ── SHA-256 helpers ────────────────────────────────────────────────────

    /** SHA-256(input) as lowercase hex (64 chars). Mirrors crypto.createHash('sha256').digest('hex'). */
    private fun sha256Hex(input: String): String {
        val md = MessageDigest.getInstance("SHA-256")
        val bytes = md.digest(input.toByteArray(Charsets.UTF_8))
        val sb = StringBuilder(bytes.size * 2)
        for (b in bytes) sb.append("%02x".format(b))
        return sb.toString()
    }

    /** SHA-256(input) as raw bytes (used to derive the HMAC key). */
    private fun sha256Bytes(input: String): ByteArray {
        val md = MessageDigest.getInstance("SHA-256")
        return md.digest(input.toByteArray(Charsets.UTF_8))
    }

    // ── HMAC-SHA256 ────────────────────────────────────────────────────────

    /** HMAC-SHA256(key, payload) as lowercase hex. */
    private fun hmacSha256Hex(key: ByteArray, payload: String): String {
        val mac = Mac.getInstance("HmacSHA256")
        mac.init(SecretKeySpec(key, "HmacSHA256"))
        val bytes = mac.doFinal(payload.toByteArray(Charsets.UTF_8))
        val sb = StringBuilder(bytes.size * 2)
        for (b in bytes) sb.append("%02x".format(b))
        return sb.toString()
    }

    // ── Machine ID ─────────────────────────────────────────────────────────

    /**
     * The hardware-bound machine ID (SHA-256 of stable device identifiers).
     *
     * Fingerprint (Android): `manufacturer|model|board|androidId|serial`
     *  - `androidId` = Settings.Secure.ANDROID_ID (stable across boot for
     *    the same app-signing-key + user; can change on factory reset).
     *  - `serial`    = Build.getSerial() on API 26+ (requires
     *    READ_PRIVILEGED_PHONE_STATE which we don't have, so it usually
     *    falls back to "unknown"), or Build.SERIAL on older APIs.
     *
     * Concatenated with '|' separator (same separator style as Electron),
     * UTF-8 encoded, SHA-256, lowercase hex (64 chars).
     *
     * IMPORTANT: This will NOT match the Electron machine ID for the same
     * physical device — Android and Electron use different identifier
     * sources. That is expected and intentional: each platform's Machine ID
     * is bound to that platform's fingerprint. Only the activation CODE
     * algorithm needs to match across platforms (and it does).
     */
    fun getMachineId(): String {
        val manufacturer = Build.MANUFACTURER ?: "unknown"
        val model = Build.MODEL ?: "unknown"
        val board = Build.BOARD ?: "unknown"

        val androidId: String = try {
            Settings.Secure.getString(
                context.contentResolver,
                Settings.Secure.ANDROID_ID
            ) ?: ""
        } catch (e: Exception) {
            ""
        }

        val serial: String = try {
            if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.O) {
                @Suppress("HardwareIds")
                Build.getSerial()
            } else {
                @Suppress("DEPRECATION")
                Build.SERIAL
            }
        } catch (e: SecurityException) {
            "unknown"
        } catch (e: Exception) {
            "unknown"
        }

        val raw = "$manufacturer|$model|$board|$androidId|$serial"
        return sha256Hex(raw)
    }

    /**
     * Short display-friendly Machine ID (first 12 chars, formatted
     * XXXX-XXXX-XXXX). Mirrors Electron's getDisplayMachineId().
     */
    fun getDisplayMachineId(machineId: String = getMachineId()): String {
        val short = machineId.substring(0, 12).uppercase(Locale.ROOT)
        return "${short.substring(0, 4)}-${short.substring(4, 8)}-${short.substring(8, 12)}"
    }

    // ── Admin Key ──────────────────────────────────────────────────────────

    /**
     * Admin key derived from the LICENSE_SECRET (used by the code generator
     * API to authorize code-generation requests).
     *
     *   adminKey = SHA-256(LICENSE_SECRET + ":admin-api-key").substring(0, 16).uppercase()
     *
     * Matches electron/license.ts, route.ts, and tools/get-admin-key.ts EXACTLY.
     */
    private fun deriveAdminKey(): String {
        val hash = sha256Hex("$LICENSE_SECRET:admin-api-key")
        return hash.substring(0, 16).uppercase(Locale.ROOT)
    }

    // ── Activation Code Generation ─────────────────────────────────────────

    /**
     * Generate the expected activation code for a (machineId, licenseType,
     * expiryMillis) triple. This is the SAME algorithm as `generateExpectedCode`
     * in electron/license.ts, route.ts, and tools/generate-license.ts:
     *
     *   expiryHex = expiryMillis.toString(16)               // lowercase hex
     *   input     = "$machineId:$licenseType:$expiryHex:$LICENSE_SECRET"
     *   hash      = SHA-256(input)                          // lowercase hex (64 chars)
     *   code      = hash.substring(0, 16).uppercase()       // 16 uppercase hex
     *   return    = "XXXX-XXXX-XXXX-XXXX"
     *
     * CRITICAL DETAIL: `expiryMillis.toString(16)` in Kotlin produces LOWERCASE
     * hex, matching JavaScript's `Number.prototype.toString(16)`. The uppercase
     * transformation happens AFTER taking the first 16 chars.
     */
    private fun generateExpectedCode(machineId: String, licenseType: String, expiryMillis: Long): String {
        val expiryHex = expiryMillis.toString(16)
        val input = "$machineId:$licenseType:$expiryHex:$LICENSE_SECRET"
        val hash = sha256Hex(input)
        val code = hash.substring(0, CODE_HASH_LENGTH).uppercase(Locale.ROOT)
        return "${code.substring(0, 4)}-${code.substring(4, 8)}-${code.substring(8, 12)}-${code.substring(12, 16)}"
    }

    /**
     * Verify an activation code against a Machine ID by brute-forcing expiry
     * dates from today (end of local day) up to 45 days ahead, end-of-day
     * each. Mirrors `verifyActivationCode()` in electron/license.ts EXACTLY.
     *
     * Returns the resolved expiry epoch-millis if valid, or null if invalid.
     *
     * IMPORTANT: The "end of day" is computed in the device's LOCAL timezone
     * (matches JavaScript's Date.setHours(23, 59, 59, 0) which also uses
     * local time). Changing the device timezone after activation may prevent
     * the brute-force from finding the original expiry — same constraint as
     * the Electron app.
     */
    private fun verifyActivationCode(machineId: String, activationCode: String): Long? {
        // Normalize: strip dashes/whitespace, uppercase
        val normalized = activationCode.replace(Regex("[-\\s]"), "").uppercase(Locale.ROOT)
        if (normalized.length != CODE_HASH_LENGTH) return null

        val formatted = "${normalized.substring(0, 4)}-${normalized.substring(4, 8)}-" +
                "${normalized.substring(8, 12)}-${normalized.substring(12, 16)}"

        val now = System.currentTimeMillis()
        val cal = Calendar.getInstance() // default timezone = device local

        for (dayOffset in 0..VERIFY_MAX_DAY_OFFSET) {
            cal.timeInMillis = now
            cal.add(Calendar.DATE, dayOffset)
            // End of local day — matches JS Date.setHours(23, 59, 59, 0)
            cal.set(Calendar.HOUR_OF_DAY, 23)
            cal.set(Calendar.MINUTE, 59)
            cal.set(Calendar.SECOND, 59)
            cal.set(Calendar.MILLISECOND, 0)

            val candidateExpiry = cal.timeInMillis
            val candidateCode = generateExpectedCode(machineId, LICENSE_TYPE_MONTHLY, candidateExpiry)
            if (formatted == candidateCode) {
                return candidateExpiry
            }
        }
        return null
    }

    // ── Public API ─────────────────────────────────────────────────────────

    /**
     * Activate a license with the given code (format: XXXX-XXXX-XXXX-XXXX).
     * Returns true on success, false if the code is invalid or expired.
     * On success, persists the license (HMAC-signed) to SharedPreferences.
     */
    fun activate(code: String): Boolean {
        val machineId = getMachineId()
        val expiryMillis = verifyActivationCode(machineId, code) ?: return false

        // Reject if the resolved expiry is already in the past (matches
        // Electron's "code was generated too long ago" check).
        if (expiryMillis < System.currentTimeMillis()) return false

        val activatedAt = System.currentTimeMillis()
        val normalizedCode = normalizeCode(code)

        persistLicense(
            code = normalizedCode,
            type = LICENSE_TYPE_MONTHLY,
            activatedAt = activatedAt,
            expiry = expiryMillis
        )
        return true
    }

    /** Deactivate / clear the current license. */
    fun deactivate() {
        val prefs = context.getSharedPreferences(PREFS_NAME, Context.MODE_PRIVATE)
        prefs.edit().remove(KEY_LICENSE_DATA).apply()
    }

    /**
     * Current license status. Reads the signed license blob from
     * SharedPreferences, verifies the HMAC, then RE-VERIFIES the activation
     * code against the current device's Machine ID (this is what binds the
     * stored license to this device — copying the blob to a different device
     * fails this check). Returns the resolved status.
     */
    fun getStatus(): LicenseStatus {
        val machineId = getMachineId()

        val stored = readAndVerifyLicense()
            ?: return inactiveStatus(machineId)

        // Re-verify the activation code against the CURRENT machine ID.
        // This is the machine-binding check — a copied blob fails here.
        val verifiedExpiry = verifyActivationCode(machineId, stored.code)
            ?: return inactiveStatus(machineId)

        // Sanity: the verified expiry must match what we stored. (Always true
        // in practice — the brute-force finds the same expiry the code was
        // generated for, as long as it's still within the 45-day window.)
        if (verifiedExpiry != stored.expiry) return inactiveStatus(machineId)

        val now = System.currentTimeMillis()
        val isExpired = stored.expiry < now

        // daysLeft = ceil((expiry - now) / 1d), clamped to 0 — matches Electron.
        val msRemaining = stored.expiry - now
        val daysLeft = if (msRemaining <= 0L) 0
            else ceil(msRemaining.toDouble() / (24.0 * 60.0 * 60.0 * 1000.0))
                .toInt().coerceAtLeast(0)

        // Per spec: active=false (incl. expired) → zero out everything
        // except machineId. The current device's machine ID is always
        // returned so the UI can always show it for re-activation.
        if (isExpired) return inactiveStatus(machineId)

        return LicenseStatus(
            active = true,
            type = stored.type,
            activatedAt = stored.activatedAt,
            expiry = stored.expiry,
            daysLeft = daysLeft,
            machineId = machineId
        )
    }

    /**
     * Generate a license code for the given machine ID and admin key.
     * (Developer tool — used by the admin code generator.)
     *
     * The admin key is `SHA-256(LICENSE_SECRET + ":admin-api-key")[:16].upper()`
     * — exactly the value that `tools/get-admin-key.ts` prints.
     *
     * The generated code is valid for 30 days from now, with the expiry
     * pinned to 23:59:59.000 LOCAL time (matches Electron generator).
     *
     * Returns the formatted code `XXXX-XXXX-XXXX-XXXX` (uppercase hex),
     * or empty string if the admin key is wrong or the machine ID is invalid.
     */
    fun generateCode(machineId: String, adminKey: String): String {
        // Validate Machine ID (must be 64-char hex SHA-256) — matches Electron.
        if (!machineId.matches(Regex("^[a-fA-F0-9]{64}$"))) return ""
        if (adminKey != deriveAdminKey()) return ""

        val cal = Calendar.getInstance() // device local timezone
        cal.add(Calendar.DATE, MONTHLY_VALIDITY_DAYS)
        cal.set(Calendar.HOUR_OF_DAY, 23)
        cal.set(Calendar.MINUTE, 59)
        cal.set(Calendar.SECOND, 59)
        cal.set(Calendar.MILLISECOND, 0)
        val expiryMillis = cal.timeInMillis

        return generateExpectedCode(machineId, LICENSE_TYPE_MONTHLY, expiryMillis)
    }

    /**
     * Full result of a license-code generation (developer tool). Mirrors the
     * JSON shape returned by the Electron `/api/generate-license` route so the
     * Android generator screen can render the same details (Display ID, type,
     * expiry, days remaining, verification badge).
     *
     * Returns null if the admin key is wrong or the machine ID is invalid.
     */
    data class GenerateResult(
        val machineId: String,
        val displayMachineId: String,
        val licenseType: String,
        val activationCode: String,
        val expiresAt: Long,
        val expiresAtFormatted: String,
        val daysRemaining: Int,
        val verified: Boolean
    )

    /**
     * Generate a 30-day license code for `machineId` authorized by `adminKey`,
     * returning the full [GenerateResult] (code + expiry + display fields).
     *
     * The expiry is pinned to 23:59:59.000 LOCAL time 30 days from today —
     * identical to the Electron generator. After generation, the code is
     * re-verified via [verifyActivationCode] to set the `verified` flag.
     *
     * Returns null on invalid input or wrong admin key (no partial result).
     */
    fun generateLicenseFull(machineId: String, adminKey: String): GenerateResult? {
        // Validate inputs (same rules as generateCode).
        if (!machineId.matches(Regex("^[a-fA-F0-9]{64}$"))) return null
        if (adminKey != deriveAdminKey()) return null

        // Compute expiry: 30 days from today, end-of-day, LOCAL timezone.
        val cal = Calendar.getInstance()
        cal.add(Calendar.DATE, MONTHLY_VALIDITY_DAYS)
        cal.set(Calendar.HOUR_OF_DAY, 23)
        cal.set(Calendar.MINUTE, 59)
        cal.set(Calendar.SECOND, 59)
        cal.set(Calendar.MILLISECOND, 0)
        val expiryMillis = cal.timeInMillis

        val code = generateExpectedCode(machineId, LICENSE_TYPE_MONTHLY, expiryMillis)
        if (code.isEmpty()) return null

        // Re-verify (should always succeed since we just generated it).
        val verifiedExpiry = verifyActivationCode(machineId, code)
        val verified = verifiedExpiry != null && verifiedExpiry == expiryMillis

        val displayId = getDisplayMachineId(machineId)
        val now = System.currentTimeMillis()
        val msRemaining = expiryMillis - now
        val daysRemaining = if (msRemaining <= 0L) 0
            else ceil(msRemaining.toDouble() / (24.0 * 60.0 * 60.0 * 1000.0)).toInt().coerceAtLeast(0)

        // Format the expiry for display: "12 Aug 2026 23:59" style.
        val fmt = java.text.SimpleDateFormat("dd MMM yyyy HH:mm", Locale.getDefault())
        val expiresAtFormatted = fmt.format(java.util.Date(expiryMillis))

        return GenerateResult(
            machineId = machineId,
            displayMachineId = displayId,
            licenseType = LICENSE_TYPE_MONTHLY,
            activationCode = code,
            expiresAt = expiryMillis,
            expiresAtFormatted = expiresAtFormatted,
            daysRemaining = daysRemaining,
            verified = verified
        )
    }

    /**
     * Validate an admin key WITHOUT generating anything. Used by the generator
     * screen to give immediate feedback if the developer enters the wrong key.
     */
    fun isValidAdminKey(adminKey: String): Boolean = adminKey == deriveAdminKey()

    // ── Persistence (HMAC-signed JSON in SharedPreferences) ────────────────

    private data class StoredLicense(
        val code: String,
        val type: String,
        val activatedAt: Long,
        val expiry: Long
    )

    /**
     * Persist the license as `payloadJson + "." + hmac` in SharedPreferences.
     *
     *  - HMAC key = SHA-256(LICENSE_SECRET) (derived, never stored directly).
     *  - payloadJson = `{"type":..,"activatedAt":..,"expiry":..,"code":..}`
     *    (key order is fixed; built manually so the same string is reproduced
     *    on read for HMAC verification).
     *
     * The Machine ID is NOT stored in the blob — machine-binding is enforced
     * on read by re-running [verifyActivationCode] against the current
     * device. This mirrors Electron's behavior, which also re-verifies the
     * activation code on every status check.
     */
    private fun persistLicense(code: String, type: String, activatedAt: Long, expiry: Long) {
        val payload = buildPayloadJson(type, activatedAt, expiry, code)
        val hmacKey = sha256Bytes(LICENSE_SECRET)
        val hmac = hmacSha256Hex(hmacKey, payload)
        val blob = "$payload.$hmac"

        val prefs = context.getSharedPreferences(PREFS_NAME, Context.MODE_PRIVATE)
        prefs.edit().putString(KEY_LICENSE_DATA, blob).apply()
    }

    private fun readAndVerifyLicense(): StoredLicense? {
        val prefs = context.getSharedPreferences(PREFS_NAME, Context.MODE_PRIVATE)
        val blob = prefs.getString(KEY_LICENSE_DATA, null) ?: return null

        val dot = blob.lastIndexOf('.')
        if (dot <= 0 || dot == blob.length - 1) return null
        val payload = blob.substring(0, dot)
        val hmac = blob.substring(dot + 1)

        // 1. Verify HMAC (constant-time compare) — prevents tampering with
        //    the expiry/code/type fields.
        val hmacKey = sha256Bytes(LICENSE_SECRET)
        val expectedHmac = hmacSha256Hex(hmacKey, payload)
        if (!constantTimeEquals(hmac, expectedHmac)) return null

        // 2. Parse the (now-trusted) payload.
        return try {
            val obj = JsonParser.parseString(payload).asJsonObject
            val type = obj.get("type")?.asString ?: return null
            val activatedAt = obj.get("activatedAt")?.asLong ?: return null
            val expiry = obj.get("expiry")?.asLong ?: return null
            val code = obj.get("code")?.asString ?: return null
            StoredLicense(code, type, activatedAt, expiry)
        } catch (e: Exception) {
            null
        }
    }

    /**
     * Build a JSON string with a STABLE key order (type, activatedAt, expiry,
     * code) and no whitespace. Built manually so the exact same string is
     * produced every time (Gson's JsonObject ordering is reliable in modern
     * versions, but manual building is bulletproof and removes any doubt
     * about HMAC determinism).
     *
     * `type` and `code` are safe to inline (always "monthly" and the
     * XXXX-XXXX-XXXX-XXXX format — no characters needing escaping).
     */
    private fun buildPayloadJson(type: String, activatedAt: Long, expiry: Long, code: String): String {
        return "{\"type\":\"$type\",\"activatedAt\":$activatedAt,\"expiry\":$expiry,\"code\":\"$code\"}"
    }

    // ── Utilities ──────────────────────────────────────────────────────────

    /** Constant-time string comparison (best-effort defense against timing attacks). */
    private fun constantTimeEquals(a: String, b: String): Boolean {
        if (a.length != b.length) return false
        var result = 0
        for (i in a.indices) {
            result = result or (a[i].code xor b[i].code)
        }
        return result == 0
    }

    /** Normalize a user-entered code to canonical XXXX-XXXX-XXXX-XXXX form. */
    private fun normalizeCode(code: String): String {
        val n = code.replace(Regex("[-\\s]"), "").uppercase(Locale.ROOT)
        if (n.length != CODE_HASH_LENGTH) return code
        return "${n.substring(0, 4)}-${n.substring(4, 8)}-${n.substring(8, 12)}-${n.substring(12, 16)}"
    }

    private fun inactiveStatus(machineId: String) = LicenseStatus(
        active = false,
        type = "",
        activatedAt = 0L,
        expiry = 0L,
        daysLeft = 0,
        machineId = machineId
    )
}

/**
 * License status snapshot.
 *
 *  - [active]: true iff a valid (HMAC-verified, machine-bound, non-expired)
 *    license is currently stored. False for "never activated" AND "expired".
 *  - [type]: "monthly" when active, "" otherwise.
 *  - [activatedAt]: epoch-millis when the current license was activated
 *    (0 if not active).
 *  - [expiry]: epoch-millis when the current license expires (always pinned
 *    to 23:59:59.000 local time on the expiry day; 0 if not active).
 *  - [daysLeft]: full days remaining, rounded UP (matches Electron's
 *    Math.ceil(...)). 0 if expired or inactive.
 *  - [machineId]: the current device's full 64-char hex Machine ID
 *    (always populated, even when inactive, so the UI can show it for
 *    re-activation).
 */
data class LicenseStatus(
    val active: Boolean,
    val type: String,          // "monthly"
    val activatedAt: Long,     // epoch millis, 0 if not active
    val expiry: Long,          // epoch millis, 0 if not active
    val daysLeft: Int,         // days remaining, 0 if expired/inactive
    val machineId: String
)
